config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt/ do
    resources :users do
      resources :my_projects, only: [:index], module: :users
    end
    resources :projects do
      member do
       post 'upvote'
      end
    end
    resource :user_sessions, only: [:new, :create, :destroy]
  end

  get '/:locale' => 'home#index', locale: /en|pt/
  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	extend FriendlyId

	has_many :projects, dependent: :destroy
	has_many :upvoted_projects, through: :fambs, source: :project
	
	EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
	scope :confirmed, -> { where.not(created_at: nil) }

	validates_presence_of :name, :email, :about, :slug

	validates_length_of :about, :minimum => 15
	validates_length_of :password, :minimum => 5

	validates_uniqueness_of :email

	validates_format_of :email, with: EMAIL_REGEXP

	has_secure_password

	has_attached_file :image, :styles => { :large => "500x500>", :medium => "300x300>", :thumb => "100x100>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  	friendly_id :name, use: [:slugged, :history]

  	def self.authenticate(email, password)
  		user = confirmed.find_by(email: email)
  		if user.present?
  			user.authenticate(password)
  		end
  	end

  	def should_generate_new_friendly_id?
  		slug.blank? || name_changed?
	end
end

app/controllers/users/my_projects_controller.rb
class Users::MyProjectsController < ApplicationController
	before_action :require_authentication, only: [:index]
	
	def index
		if params[:p].blank?
			@current_user_projects = current_user.projects.all.order("created_at DESC").page(params[:page]).per(6)
		else
			@search_mine = params[:p]
			my_projects_searched = current_user.projects.search(@search_mine)
			@current_user_projects = my_projects_searched.all.order("created_at DESC").page(params[:page]).per(6)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_no_authentication, only: [:new, :create]
	before_action :can_change, only: [:edit, :update]

	def show
		@user = User.friendly.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to @user, notice: t('flash.notice.user_created')
		else
			render action: :new
		end
	end

	def edit
		@user = User.friendly.find(params[:id])
	end

	def update
		@user = User.friendly.find(params[:id])
		if @user.update(user_params)
			redirect_to @user, notice: t('flash.notice.user_updated')
		else
			render action: :edit
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :about, :password, :password_confirmation, :image)
	end

	def can_change
		unless user_signed_in? && current_user == user
			redirect_to user_path(params[:id])
		end
	end

	def user
		@user ||= User.friendly.find(params[:id])
	end
end

app/views/users/_form.html.erb
<div class="formin">
	
	<%= form_for @user, :html => {:multipart => true} do |f| %>
		
		<div class = "formin_group">
			<div class="label_form"><%= f.label :name %></div> 
			<%= f.text_field :name, class: 'form-control' %>
			<%= error_tag @user, :name %>
		</div>

		<div class = "formin_group">
			<div class="label_form"><%= f.label :email %></div> 
			<%= f.text_field :email, class: 'form-control' %>
			<%= error_tag @user, :email %>
		</div>

		<div class = "formin_group">
			<div class="label_form"><%= f.label :password %></div> 
			<%= f.password_field :password, class: 'form-control' %>
			<%= error_tag @user, :password %>
		</div>

		<div class = "formin_group">
			<div class="label_form"><%= f.label :password_confirmation %></div> 
			<%= f.password_field :password_confirmation, class: 'form-control' %>
			<%= error_tag @user, :password_confirmation %>
		</div>

		<div class = "formin_group">
			<div class="label_form"><%= f.label :image %></div> 
			<%= f.file_field :image, class: 'form-control' %>
			<%= error_tag @user, :image %>
		</div>

		<div class = "formin_group">
			<div class="label_form"><%= f.label :about %></div> 
			<%= f.text_area :about, class: 'form-control' %>
			<%= error_tag @user, :about %>
		</div>

		<div class = "formin_group">
			<%= f.submit class: "btn btn-success" %>
		</div>

	<% end %>

</div>

app/views/users/edit.html.erb
<div class="header_users_bar">
	<div class="header_users">
		<%= t '.title' %>
	</div>
</div>

<%= render 'form' %>

<div class="links_users">
	<button type="button" class="btn btn-warning"><%= link_to t('.links_show'), @user %></button>
</div>

app/views/users/new.html.erb
<div class="header_users_bar">
	<div class="header_users">
		<%= t '.title' %>
	</div>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="show_page">
	<% if @user.image.present? %>
		<div class = "image_show">
			<%= image_tag @user.image.url(:medium) %>
		</div>
	<% end %>

	<ul class="list-group">
  		<li class="list-group-item", style="text-align:center;font-size:22px;">
  			<b><%= t('.name') %></b>
  		</li>

		<li class="list-group-item", style="text-align:center;font-size:20px;font-family: 'Merienda', cursive;">
			<%= @user.name %>
		</li>
	</ul>

	<ul class="list-group">
  		<li class="list-group-item", style="text-align:center;font-size:22px;">
  			<b><%= t('.about_project') %></b>
  		</li>
  		
		<li class="list-group-item", style="text-align:center;font-size:20px;font-family: 'Merienda', cursive;">
			<%= @user.about %>
		</li>
	</ul>

</div>

<% if user_signed_in? && current_user == @user %>
	<div class="links_users">
		<button type="button" class="btn btn-warning">
			<%= link_to t('.links_edit'), edit_user_path(@user) %>
		</button>
	</div>
<% end %>