config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt/ do
    resources :users do
      resources :my_projects, only: [:index], module: :users
    end
    resources :projects do
      member do
       post 'upvote'
      end
    end
    resource :user_sessions, only: [:new, :create, :destroy]
  end

  get '/:locale' => 'home#index', locale: /en|pt/
  root 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	extend FriendlyId
	belongs_to :user
	belongs_to :category
	has_many :fambs, dependent: :destroy
	has_many :upvoted_users, through: :fambs, source: :user

	FACEBOOK_REGEX = /\A(https?:\/\/)?(?:www\.)?facebook\.com\/(?:(?:\w)*#!\/)?(?:pages\/)?(?:[\w\-]*\/)*([\w\-\.]*)/
	VIDEO_REGEX = /\A(?:https?:\/\/)?(?:www\.)?youtu(?:\.be|be\.com)\/(?:watch\?v=)?([\w-]{10,})/
	URL_REGEX =  /\A((http|https):\/\/)(([a-z0-9-\.]*)\.)?([a-z0-9-]+)\.([a-z]{2,5})(:[0-9]{1,5})?(\/)?/

	validates_presence_of :name, :about, :slug

	validates_uniqueness_of :name

	validates_format_of :video, with: VIDEO_REGEX, allow_blank: true
	validates_format_of :facebook_page, with: FACEBOOK_REGEX, allow_blank: true
	validates_format_of :website, with: URL_REGEX, allow_blank: true

	has_attached_file :image_proj, :styles => { :large => "500x500>", :medium => "300x300>", :thumb => "100x100>" }
  	validates_attachment_content_type :image_proj, :content_type => /\Aimage\/.*\Z/

  	friendly_id :name, use: [:slugged, :history]

	validates_length_of :about, minimum: 15

	def should_generate_new_friendly_id?
  		slug.blank? || name_changed?
	end

	def self.search(query)
		if query.present?
			where(['name LIKE :query or about LIKE :query', query: "%#{query}%"])
		else
			all
		end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :require_authentication, only: [:new, :create, :edit, :update, :upvote]
	before_action :set_users_projects, only: [:edit, :update, :destroy]
	
	

	def index
		if params[:q].blank? && params[:category].blank?

			@projects = Project.all.order("fambs_count DESC").page(params[:page]).per(6)

		elsif params[:q].present? && params[:category].blank?

			@search = params[:q]
			projects_searched = Project.search(@search)
			@projects = projects_searched.all.order('fambs_count DESC').page(params[:page]).per(6)

		elsif params[:q].blank? && params[:category].present?

			@category_id = Category.find_by(name_en: params[:category]).id
			@projects = Project.where(category_id: @category_id).order("fambs_count DESC").page(params[:page]).per(6)

		elsif params[:q].present? && params[:category].present?

			@category_id = Category.find_by(name_en: params[:category]).id
			@search = params[:q]
			projects_with_category = Project.where(category_id: @category_id).order("fambs_count DESC")
			projects_searched_with_category = projects_with_category.search(@search)
			@projects = projects_with_category.all.order('fambs_count DESC').page(params[:page]).per(6)

		end
	end

	def show
		@project = Project.friendly.find(params[:id])
		@code = @project.video.split('=');
		@yt_code = @code[1]
	end

	def new
		@project = current_user.projects.build
	end

	def create
		@project = current_user.projects.build(project_params)

		if @project.save
			redirect_to @project, notice: t('flash.notice.project_created')
		else
			render action: :new
		end
	end

	def edit
		
	end

	def update
		
		if @project.update(project_params)
			redirect_to @project, notice: t('flash.notice.project_updated')
		else
			render action: :edit
		end
	end

	def destroy
		@project.destroy
		redirect_to root_path, notice: t('flash.notice.project_destroyed')
	end

	def upvote
		@project = Project.friendly.find(params[:id])
		
	    if @project.fambs.create(user_id: current_user.id) && @project.fambs_count_changed?
			redirect_to @project
	    else
	    	redirect_to @project, alert: t('flash.alert.already_fambed')
	    end
	    
	end

	private

	def project_params
		params.require(:project).permit(:name, :about, :facebook_page, :video, :website, :image_proj, :category_id, :famb)
	end

	def set_users_projects
		@project = current_user.projects.friendly.find(params[:id])
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def belongs_to_user(project)
		user_signed_in? && project.user == current_user
	end
end

app/views/projects/_form.html.erb
<div class="formin_projects">
	
	<%= form_for @project, :html => {:multipart => true} do |f| %>
		
		<div class = "formin_group_projects">
			<div class="label_form_projects"><%= f.label :name %></div> 
			<%= f.text_field :name, class: 'form-control' %>
			<%= error_tag @project, :name %>
		</div>
		
		<% if I18n.locale == :pt %>
			<div class="formin_group_projects">
				<%= f.collection_select :category_id, Category.all, :id, :name_pt, { prompt: "Escolha uma categoria" } %>
			</div>
		<% else %>
			<div class="formin_group_projects">
				<%= f.collection_select :category_id, Category.all, :id, :name_en, { prompt: "Choose a category" } %>
			</div>
		<% end %>

		<div class = "formin_group_projects">
			<div class="label_form_projects"><%= f.label :video %></div> 
			<%= f.text_field :video, class: 'form-control' %>
			<%= error_tag @project, :video %>
		</div>

		<div class = "formin_group_projects">
			<div class="label_form_projects"><%= f.label :website %></div> 
			<%= f.text_field :website, class: 'form-control' %>
			<%= error_tag @project, :website %>
		</div>

		<div class = "formin_group_projects">
			<div class="label_form_projects"><%= f.label :facebook_page %></div> 
			<%= f.text_field :facebook_page, class: 'form-control' %>
			<%= error_tag @project, :facebook_page %>
		</div>

		<div class = "formin_group_projects">
			<div class="label_form_projects"><%= f.label :image_proj %></div> 
			<%= f.file_field :image_proj, class: 'form-control' %>
			<%= error_tag @project, :image_proj %>
		</div>

		<div class = "formin_group_projects">
			<div class="label_form_projects"><%= f.label :about %></div> 
			<%= f.text_area :about, class: 'form-control' %>
			<%= error_tag @project, :about %>
		</div>

		<div class = "formin_group_projects">
			<%= f.submit class: "btn btn-success" %>
		</div>

	<% end %>

</div>

app/views/projects/edit.html.erb
<div class="header_projs_bar">
	<div class="header_projs">
		<%= t '.title' %>
	</div>
</div>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="input-group">
  <%= form_tag projects_path, method: :get do %>
    <%= text_field_tag :q, @search, class: 'form-control', :placeholder => t('.placeholder_search') %>
    <button type="submit" class="button_search"><span class="glyphicon glyphicon-search"></span></button>
  <% end %>
</div>

<br> <br>
	
<% if I18n.locale == :pt %>
	<div class="categories">
		<% Category.all.each do |category| %>
			<button type="button" class="btn btn-default">
				<%= link_to category.name_pt, projects_path(category: category.name_en) %>
			</button>
		<% end %>
	</div>
<% else %>
	<div class="categories">
		<% Category.all.each do |category| %>
			<button type="button" class="btn btn-default">
				<%= link_to category.name_en, projects_path(category: category.name_en) %>
			</button>
		<% end %>
	</div>
<% end %>

<br>

<% if @projects.count == 0 %>
	<div class = "no_projects_index"><%= t('.no_projects_founded') %></div>
<% else %>
	<% @projects.each do |project| %>
		<div class="projects_index_background">
			<div class="project_index_name">
				<%= link_to project.name, project %>	
			</div>
			
			<div class="project_index_about">
				<%= truncate(project.about, length: 30) %>
			</div>
		</div>
	<% end %>
<% end %>


<div class="pagination_position">
	<%= paginate @projects, :theme => 'twitter-bootstrap-3'  %>
</div>

app/views/projects/new.html.erb
<div class="header_projs_bar">
	<div class="header_projs">
		<%= t '.title' %>
	</div>
</div>

<%= render 'form' %>

app/views/projects/show.html.erb
<% if belongs_to_user(@project) %>
	<ul class="nav nav-pills nav-justified">
  		<li role="presentation">
  			<%= link_to t('.links_edit_project'), edit_project_path(@project) %>
  		</li>

  		<li role="presentation">
  			<%= link_to t('.destroy'), project_path(@project), method: :delete, data: { confirm: t('dialogs.destroy') } %>
  		</li>
  	</ul>
<% end %>


<% if user_signed_in? && @project.user != current_user %>
	<ul class="nav nav-pills nav-justified">
		<li role="presentation">
			<%= link_to t('.links_famb_it'), upvote_project_path(@project), method: :post, data: { disable_with: t('.wait_famb') } %>
		</li>
	</ul>
<% end %>


<div class="project_name">
	<%= @project.name %>     <span class="fambs_count">(<%= @project.fambs.count %> Fambs)</span>
</div>

<div class="project_about">
	<%= @project.about %>
</div>

<div class="author_show">
	<%= t('.author_project') %> <%= link_to @project.user.name, @project.user, target: "_blank" %>
</div>

<% if @project.website.present? %>
	<ul class="list-group">
  		<li class="list-group-item", style="text-align:center;font-size:18px;"><b>Website</b></li>
		<li class="list-group-item", style="text-align:center;font-size:16px;">
			<%= link_to @project.website, @project.website, target: "_blank" %>
		</li>
	</ul>
<% end %>

<% if @project.facebook_page.present? %>
	<ul class="list-group">
  		<li class="list-group-item", style="text-align:center;font-size:18px;"><b><%= t 'projects.show.page_fb' %></b></li>
		<li class="list-group-item", style="text-align:center;font-size:16px;">
			<%= link_to @project.facebook_page, @project.facebook_page, target: "_blank" %>
		</li>
	</ul>
<% end %>

<% if @project.image_proj.present? %>
	<div class="image_show">
		<img><%= image_tag @project.image_proj.url(:medium) %></img>
	</div>
<% end %>

<% if @project.video.present? %>
	<div class="video_show">
		<iframe width="100%" height="500" src="https://www.youtube.com/embed/<%= @yt_code %>" frameborder="0" allowfullscreen></iframe><br>
	</div>	
<% end %>