config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt/ do
    resources :users do
      resources :my_projects, only: [:index], module: :users
    end
    resources :projects do
      member do
       post 'upvote'
      end
    end
    resource :user_sessions, only: [:new, :create, :destroy]
  end

  get '/:locale' => 'home#index', locale: /en|pt/
  root 'home#index'

end

app/views/layouts/_user_navbar.html.erb
<div class = "navbar">
	<div class="nav_each">
    	<%= link_to "Home", root_path, class: 'btn btn-primary' %>
    	<%= link_to t('layouts.nav_user.new_project'), new_project_path, class: 'btn btn-primary' %>
    	<%= link_to t('layouts.nav_user.signout'), user_sessions_path, method: :delete, class: 'btn btn-primary' %>

    	<%= link_to t('layouts.nav_user.my_profile'), user_path(current_user), class: 'btn btn-primary' %>

    	<%= link_to t('layouts.nav_user.my_projects'), user_my_projects_path(current_user.id), class: 'btn btn-primary' %>

    	<%= link_to t('layouts.nav_visitor.projects_index'), projects_path, class: 'btn btn-primary' %>
	</div> 
</div>

app/views/layouts/_visitor_navbar.html.erb
<div class = "navbar">
	<div class="nav_each">
		<%= link_to t('layouts.nav_visitor.signup'), new_user_path, class: 'btn btn-primary' %>
    	<%= link_to "Home", root_path, class: 'btn btn-primary' %>
		<%= link_to t('layouts.nav_visitor.login'), new_user_sessions_path, class: 'btn btn-primary' %>
		<%= link_to t('layouts.nav_visitor.projects_index'), projects_path, class: 'btn btn-primary' %>
	</div> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProShare</title>

  <link href='http://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Cinzel' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Merienda' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Exo+2' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice.present? %>
	<div class="alert alert-success" role="alert"><%= notice %></div>
<% end %>

<% if alert.present? %>
	<div class="alert alert-warning" role="alert"><%= alert %></div>
<% end %>

<% if user_signed_in? %>
  <%= render 'layouts/user_navbar' %>
<% else %>
  <%= render 'layouts/visitor_navbar' %>
<% end %>

<%= yield %>

</body>
</html>